name: Push-to-EC2
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Copy files with SSH
        run:
          scp -i ${{secrets.EC2_SSH_KEY}} -r ./
          ec2-user@ec2-18-231-148-75.sa-east-1.compute.amazonaws.com:~/pantayas/

  build:
    name: Build and Start Application
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Run Commands
        run: |
          ssh -i ${{secrets.EC2_SSH_KEY}} ec2-user@ec2-18-231-148-75.sa-east-1.compute.amazonaws.com "
            cd ~/pantayas
            pkill -f 'vite'
            npm install
            npm run start
          "
